spring:
  datasource:
    username: root
    password: Aa+123456
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&characterEncoding=UTF8
    driver-class-name: com.mysql.cj.jdbc.Driver
  quartz:
    jdbc:
      initialize-schema: always
    job-store-type: jdbc
    overwrite-existing-jobs: on
  web:
    resources:
      static-locations:

server:
  port: 80



#logging:
#  level:
#    root: debug
#    com.he.multi: debug
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file:
#    path: D:\software\developmentTools\log\myapp.log